### ISSUE TITLE
Cheating by removing the cookies

### ISSUE THREAD

**Issue by AAllport** [Festify/app#125]
Currently, people can cheat by deleting the cookies and refreshing.
I propose a fix by adding some sort of ID such as fingerprintjs to prevent this.
I would be happy to add this myself, however, I feel someone with more experience with this code will be able to implement quicker
Many Thanks
A

**Comment by NeoLegends** [comment]
Hey @AAllport!

This is definitely something we know needs fixing. As you may know, libraries like fingerprintjs can never guarantee 100% user identification, though, because they inherently rely on information provided by the browser, which can easily be faked by simple things like incognito mode, or more advanced funtionality like user agent or cookie editor browser plugins. In fact, the main purpose of incognito mode in browsers is preventing fingerprinting and appearing like a new user every time.

Thus, the solution we envision is allowing the party host to require his guests to sign in via a social login provider (like Facebook, Google+, Twitter, etc.) to be able to vote. This is the only way to reliabily guarantee that only one vote per user is cast (modulo multiple accounts).

We already have issue #23 tracking that, so I'm going to close this in favor of that one. :)

**Comment by NeoLegends** [comment]
If you have any more questions or want to offer help, please don't hesitate posting either in this issue, if you don't agree with my reasoning, or in #23.

**Comment by AAllport** [comment]
Can I ask what the timeline is for #23, I'm aware that a user can fake a fingerprint, however, if the social logins will take a significant period of time would it not be better implementing the fingerprint. Or, assign different levels of security dictated by the host. Either no security (current implementation), fingerprinting or social (at the highest level)?
Please do not take my response as a devaluation of festify as it is a well-written system

**Comment by NeoLegends** [comment]
> Please do not take my response as a devaluation of festify as it is a well-written system

All is well, no worries. :)

> if the social logins will take a significant period of time would it not be better implementing the fingerprint

Do you mean implementation-wise or user-wise? Social logins are super quick for the users, because all it takes is one redirect to the login page of the provider of choice (there will be multiple), and that's it. In fact, that's _the_ reason why we're doing social logins in the first place.

> Or, assign different levels of security dictated by the host. Either no security (current implementation), fingerprinting or social (at the highest level)?

Hmm, sounds reasonable from a distance. I think we'd need to take a closer look at fingerprintjs' accuracy and how we'd integrate such a system with Firebase to make a reasonable decision here.

**Comment by AAllport** [comment]
> Do you mean implementation-wise or user-wise?
I was referring to implementation time, I'm aware that social logins with f.base are rather quick to complete 
> how we'd integrate such a system with Firebase
When you implement the social login, will this replace the instance id, or something different?

If a PR was made to replace the random instance with a fingerprint, what is the likelihood of it being accepted? Or is SSO likely to be in the next update to the site first?

**Comment by NeoLegends** [comment]
> When you implement the social login, will this replace the instance id, or something different?

The votes are based on the firebase user ID, not the `instanceId` you may have read about. Thus, you'd need to hook that into firebase's (currently anonymous) authing, which might be a little more work. The `instanceId` is used to identify a single tab running Festify and is used to a) identify the instance that's currently playing music and b) seamlessly transfer playback between tabs or devices.

> If a PR was made to replace the random instance with a fingerprint, what is the likelihood of it being accepted?

I would be open to accepting it, given its written well. :) We will focus our efforts on proper social login first, though.

>  Or is SSO likely to be in the next update to the site first?

Since we have CD attached, we have lots of very small deploys, so technically its very unlikely that that feature will make it into the next deployment, but it will surely find its way into the next bigger update / deployment.
