### ISSUE TITLE
Icon in not Admin mode seems wrong

### ISSUE THREAD

**Issue by acethatch** [Festify/app#134]
The icon of the current song in not Admin mode seems wrong (A pause icon).
Now it looks if you could click it to start playing.

Maybe the play icon or an empty one is _better_?

![2018-03-30 23_10_34-festify](https://user-images.githubusercontent.com/360258/38154399-0c774ba0-3472-11e8-9353-8807b54541fc.png)

![2018-03-30 23_10_34-festify clear](https://user-images.githubusercontent.com/360258/38154406-118dd5d2-3472-11e8-9a96-06bf271cabe4.png)

**Comment by NeoLegends** [comment]
The icon always indicates the current playback state, and I personally don‘t want to change that. Think of media players like VLC, they also show the pause icon when something is playing because that‘s what you‘d do when you‘d click the button. 

Furthermore, this would make the UI inconsistent, because the button would suddenly change its appearance once you‘re party admin. Right now the only thing that happens when you‘re admin is that the button isn‘t disabled anymore, which is the better option in my opinion. :)

**Comment by leolabs** [comment]
We could remove the button altogether for non-admin users as it is of no use to them. The playback state is visible in the progress bar which is grayed out when the player is paused. That could improve the UX for party guests and unclutter the UI a bit more :)
