### ISSUE TITLE
No playback ; chrome ; os x

### ISSUE THREAD

**Issue by ErezHorev** [Festify/app#169]
I would really like to use your service but i have no playback at all (nor my friends at office).
This issue seems to be very common here.

Why isn't that being shown with a friendly message with instructions on how to solve?
I have no idea how to solve it. what should be installed? from where?

The links on @bih response seems for experts, no way i'm going to spend more than a minute on this.

IMO think you should get this covered if want users to stay your users rather than another service

Everything else on your web site looks perfect but doesn't give any value if no playback.
Sadly will move to other service.

Hope you could aid/fix quickly

Thanks ;)

I'm using macbook OSx 10.13.3 with chrome

*commented the also on https://github.com/spotify/web-playback-sdk/issues/10

**Comment by leolabs** [comment]
Hey man,
thanks for your bug report! 

Could you further elaborate on which version of macOS and Chrome you're using, which country you are located at and maybe provide a party id where the playback doesn't work?

Did playback work for you before or has it never worked?

**Comment by NeoLegends** [comment]
Hey!

> I would really like to use your service but i have no playback at all (nor my friends at office).

Are you using Spotify Premium accounts to login? Are you using desktop or mobile devices?

> The links on @bih response seems for experts, no way i'm going to spend more than a minute on this.

Did you come here from our FAQs and clicked the link for background information? To be fair, this _is_ for experts and that's why we put the link under background information and didn't write about the underlying issue in the FAQ text directly. Seems like we didn't express ourselves clearly enough though, so I'll update the FAQs to specifically say that the link is for web experts. :)

**Comment by leolabs** [comment]
On another topic, @NeoLegends, maybe we should show an error when non-premium Spotify users try to log in to Festify. This has been a confusing thing for multiple users in the past and should be fairly easy to check for :)

**Comment by NeoLegends** [comment]
Yep!

**Comment by ErezHorev** [comment]
Hi @leolabs 
Thanks for the quick response 👍 
It never worked before, first time we try it.
We're trying Party ID: 989869  ([https://festify.us/party/-LB00-RaL8uygsPWniVZ])

-- INFO --
Location: Israel
macOS version:  10.13.3 (17D47)
Chrome version:  65.0.3325.181 (Official Build) (64-bit)

**Comment by ErezHorev** [comment]
@NeoLegends , @leolabs 

> Are you using Spotify Premium accounts to login? 
No.  is it mandatory for make it work?

> Are you using desktop or mobile devices?
desktop

**Comment by NeoLegends** [comment]
>

**Comment by NeoLegends** [comment]
> No. is it mandatory for make it work?

Yes, Spotify only allows streaming if the account is a premium account. :) this is probably the underlying issue here. If you login with a Spotify Premium-account it will work. :)

**Comment by ErezHorev** [comment]
Oh...
I'll try again with premium account soon and report.

As @leolabs said before
You guys **## must prevent from one to login if his account is non-premium with a big clear friendly message.**
Thanks

**Comment by NeoLegends** [comment]
Noted down ✅

Feel free to reopen this ticket if you‘re still facing issues. :)

**Comment by ErezHorev** [comment]
It works OK when using premium account 👍 
thanks

Consider that if you bound your service to only premium users than it might hurt your popularity since all must have premium account (already heard some negative opinions about it here).
I suggest that non-premium users could participate the party and just effect the control of the songs (vote/skip..etc).

You'll understand my point through my use case:
We're 5 persons in office, i created a party and shared with team mates, only my pc is playing the music with some kickass speakers **but** everyone else can control/vote party songs from their own pc.

We actually thinking on dedicating a different unused computer for it with large screen showing the TV mode.

One last (non-related) thing
Does your service allows skip to next song (immediately) using some down-voting ? i would really like the ability to set threshold of downvote to skip songs. 

Thanks again

**Comment by NeoLegends** [comment]
> It works OK when using premium account 👍

Great!

> I suggest that non-premium users could participate the party and just effect the control of the songs (vote/skip..etc)

Skipping is usually tied to the ability of playback, so we don't currently have that. Think the other way around: wouldn't it be weird if you could skip, but not play?
You don't need an account to vote, just open the party and start voting. :) We tried to make the party joining process as friction-less as possible to get as many people as possible to vote. 

> Does your service allows skip to next song (immediately) using some down-voting ? i would really like the ability to set threshold of downvote to skip songs.

We don't currently have this, but we thought about this as well. #86 tracks this.

We have explicitly decided _against_ downvotes because it clutters the user interface and we don't really see a benefit. Having upvotes only favors a positive vibe, and we favor the attitude: If you don't like a track, suggest something better instead of "disliking" something that exists. :)
In #86 we would introduce a special "downvote" or a "skip vote" just for the current track that, when a certain threshold is reached, just skips the track, as you invisioned. The exact details on how we would implement this, UI & UX-wise, is still TBD, though.

**Comment by ErezHorev** [comment]
yep [#86 ](https://github.com/Festify/app/issues/86) is what i need.

I respect your approach but IMHO its not a matter if positive/negative vibes. 

your service allows a collaborative playlist that might be broadcasted from a single point (like my use case) in which that case we want it to be a democratic like playlist which majority does counts.

Again, my use case ,single broadcast point (in oppose to many users using headphones) really desires that killer feature since there is no way i'm going to be the office DJ and skip songs on each ones request. 
Maybe, to answer all use cases, you can consider to let the user define the behaviour. disable threshold by default unless user explicitly decided otherwise.

Thanks

**Comment by ErezHorev** [comment]
I don't understand something. 

> because the top tracks are the popular ones people want to hear. So if your crowd / office people vote a lot, there won‘t be the need to skip often.

are you saying that songs play order is effected by votes?

**Comment by NeoLegends** [comment]
> are you saying that songs play order is effected by votes?

Yes, this is what Festify is all about and what sets it apart from other social jukeboxes. 😅

**Comment by ErezHorev** [comment]
😅 x100
sorry for missing this core spot (saw it now also on your main page)
