### ISSUE TITLE
Include the party code as an URL parameter, instead of the party id. 

### ISSUE THREAD

**Issue by kimrtaylor** [Festify/app#193]
It's often easier to share a complete URL and easier for users to navigate directly to the url instead of manually entering the party code. E.g. When users aren't in the same room (in advance of a party).

Using party codes is more user friendly than party ids, e.g. https://festify.us/123456

However even with the long party id, it is often easier to copy and paste the complete url rather than the URL plus the code. I.e.  When on the 'share' page, we should display the full URL including the party code / party id), so that the admin can easily copy it and share with friends. Even better would be a 'copy to clipboard' button.

**Comment by stevebrowndotco** [comment]
+1

**Comment by NeoLegends** [comment]
Thanks for the suggestion! We're aware of deficiencies here. We also have some old issue lying around kinda covering this #20. :D I think I'm going to close that one in favor of this one here.

---

Back on topic:

I think we should go for a middle ground here. URLs like `festify.us/123456` are not going to be stable over time, because there are just far too few party codes for all Festify parties that have been / will be created. Last time I checked we had ~500 collisions _already_. The current URL / long ID is long enough to guarantee uniqueness until basically the end of the universe. This means: Keep the current URL form, but redirect from `festify.us/<Short Party Code>` to `festify.us/party/<Long Party ID>`. This would make sharing the short URL possible whilst keeping most of the benefits of the long URL.
