### ISSUE TITLE
Invite codes for individual people in a party

### ISSUE THREAD

**Issue by PolkaHard** [Festify/app#256]
So we use this tool at our office (Thanks for the great tool!). But we came across an issue with up-voting songs. This feature is awesome but people can take advantage of multiple browser tabs to up-vote the song they want and it is impossible to track this. 

What I would like to have is an invite tab where I can send colleagues there own invite code to join the room/party which only works once. So they can't have multiple sessions in a party.

**Comment by NeoLegends** [comment]
Just turn on `Require guests to sign in before voting` in the settings tab. It'll force the people to login using a social account and the votes will be tied to that account. :)

Multiple accounts using the same e-mail address will be merged, so that you won't be able to bypass the feature even if you use e. g. Facebook and Google+ (as long as you used the same e-mail address).

**Comment by PolkaHard** [comment]
> Just turn on `Require guests to sign in before voting` in the settings tab. It'll force the people to login using a social account and the votes will be tied to that account. :)
> 
> Multiple accounts using the same e-mail address will be merged, so that you won't be able to bypass the feature even if you use e. g. Facebook and Google+ (as long as you used the same e-mail address).

Well I just read over that. Thanks for the great tool!
