### ISSUE TITLE
Anonymous checks can be circumvented

### ISSUE THREAD

**Issue by Mstrodl** [Festify/app#264]
The optional anonymous user blocking can be (rather easily) circumvented using email and password authentication which doesn't require email verification. Although it's not supported by the web UI, it's relatively easy to write a script to sign up for a bunch of accounts and vote with all of them:

```js
await FireBase.auth().createUserWithEmailAndPassword(
  `thisemaildoesnotexist${lastId++}@example.org`,
  "somepassword"
);
```

I believe [this](https://github.com/Festify/app/blob/bb8feff61968bdd121cfed0bea91e8df87d6cefc/database.rules.bolt#L95) is the offending line, but I'm not sure what the id of the provider is for email accounts. This could be fixed a few ways:
 - By disabling email and password signup for the Firebase console
 - By adding email signup to the existing anonymous provider check
 - By checking if the email is verified on the anonymous provider check

(Or some combination of these)

Also: huge props on making a voting music system! I had been wanting to write something like it for a while!

**Comment by NeoLegends** [comment]
Hey! Thank you for your findings!

The anonymous authentication system can be bypassed rather easily, yes! The simplest way to circumvent it is to actually just delete your browser cache or visit Festify using an incognito browser session. This is, however, known, and there's no solid way to fix it for the anonymous, "simple" enter-party-code-and-vote case.

For the cases where it matters, Festify also has a mode where it requires your guests to sign in via a social provider such as Facebook, Google or Twitter. This is safe and cannot be bypassed, as long as people use a limited set of email addresses for their social accounts (most do). Just go to the settings and toggle "Require party guests to sign in before voting".

While it works really well at preventing fraut, this mode is not the default because we found that it raises the barrier for people to start voting rather heavily. Usually voting fraud at Festify parties is not that big a deal (at least for "smaller" parties < 50 guests) to warrant the reduced amount of people voting.

Best regards!

**Comment by Mstrodl** [comment]
@NeoLegends You seem to misunderstand, the social provider can be bypassed by doing what I described above ^

**Comment by NeoLegends** [comment]
Oh, I see! Thanks.

> By disabling email and password signup for the Firebase console

I think this is the way to go. I'll consult the teammates to check whether this would break anything, but that would be a rather trivial change. :)

**Comment by Mstrodl** [comment]
@NeoLegends Personally, I think email should be disabled in Firebase and add another check to the anonymous provider check just in case someone wants to host Festify themselves. AFAIK, Firebase doesn't have email and password signup enabled by default, but it definitely couldn't hurt to add the check just in case.

**Comment by NeoLegends** [comment]
> Firebase doesn't have email and password signup enabled by default, but it definitely couldn't hurt to add the check just in case.

Ah, think I'll leave the check out for the moment, because we might add an E-Mail & PW sign in later on, but I just turned off Email + PW registration. Firebase actually has none of the providers enabled by default. I'd just like to see them allow this be configured via code.
