### ISSUE TITLE
Playback stops and cannot be resumed unless skipping track

### ISSUE THREAD

**Issue by dantegt** [Festify/app#272]
Hi there! We've experienced an unexpected beheaviour with Festify. At some point of playback, I couldn't figure out a reason why, it would stop playing the current track and won't respond to pause/play the track. No errors in console.

Reloading the page gets the list again with the stopped track but pressing play won't work. 
The only way to resume playback is skipping that track (sometimes at the expense of 💔)

Let me know if I can provide more information about this. Thanks!

**Comment by DrGigabyte** [comment]
I have seen this too. Also, playback stopping and having to refresh browser to restart.

I read that it might be due to me logging into phone as admin so I tested, and that was it. I was logging in with an older slow phone, but it also happened once on a fast phone.

So, checked all of my devices and and logged out everywhere (except the player). When I used the phone without logging in as admin, just to look at the queue, it happened again.

I finally went to every device (all Android) and cleared both the application cache and data. That seems to have fixed it. 

I'll leave it running for a few days and see if it glitches again.

**Comment by leolabs** [comment]
Thanks, that's a good insight! We'll try to reproduce the behavior with multiple devices logged in as admin. Maybe that is the bug's root cause.

**Comment by DrGigabyte** [comment]
Had the error again a few times. To get it started again pressed F5 - reload page. If I try to start the song that stopped, no sound. Skip to next song and it started working again.

Here is a copy of the log after is failed and before I restarted

[festify 20190530-1426.log](https://github.com/Festify/app/files/3261712/festify.20190530-1426.log)

**Comment by DrGigabyte** [comment]
I also had problems with songs being skipped. It looks like there are 2 types of errors in the log:

    - Cross-Origin Request Blocked (CORS)
    - Firefox can’t establish a connection to the server at wss://s-usc1c-nss-233.firebaseio.com/...

It seemed that the CORS error happened mostly when songs were skipped.

I noticed the firebase.io problem when palyback stopped. 

Problem occurred in both Firefox and Chrome. There is a Firefox add-on: "CORS Everywhere". I have not had a chance to test this yet. 

I also found some code snippets for dealing with CORS in javascript. Here is one [[article],](https://benjaminhorn.io/code/setting-cors-cross-origin-resource-sharing-on-apache-with-correct-response-headers-allowing-everything-through/)
