### ISSUE TITLE
qr-code

### ISSUE THREAD

**Issue by AlexanderSch90** [Festify/app#282]

**Comment by AlexanderSch90** [comment]
On the last Party I have generate a QR-Code for the "Partylink" it was even better than let the people past the code... 
It was nice if you can implementate a JPG oder direkt QR-Code in the TV-Mode!

Thanks!

**Comment by NeoLegends** [comment]
Hey :)

Thank you for the suggestion!

Indeed, we did feature a QR code in TV Mode before, but removed it because it cluttered the UI too much and people didn't like it. We figured generating one yourself isn't too hard a task for the people that want one.

Perhaps though, we could generate one in the share menu such that people who don't know how they would generate one can get one without much effort. I'll open another issue for that. :)
