### ISSUE TITLE
Festify is glitching - beginning of track is looping and unable to skip songs

### ISSUE THREAD

**Issue by JeremiahsJukebox** [Festify/app#314]
Full songs aren't playing, instead we're getting a loop of the first few seconds of the song. If you try to skip the song, the same song continues and the page freezes. This was on a PC with both Chrome and Microsoft Edge

Tried to replicate on mobile but no sound plays.

**Comment by leolabs** [comment]
I just took a look and think I found the bug. Spotify changed the HTTP status codes of their responses which led Festify to believe that the playback request didn't succeed, so we retried ~5s later. This is fixed in 5ef4227464768a8b6afc7aa369cc486c6ee38fa3.

Let us know if this solves the issues on your side :)
